using System;
using System.Collections.Generic;
using System.Linq;
using System.Xml.Linq;
using Razer.ActionService;

namespace Razer.AccountManager
{
	public class UserProfileIncompleteException : Exception, IRazerSerializable
	{
		public string RazerId { get; set; }

		public bool RazerIdAutoGenerated { get; set; }

		public bool NeedsNewsLetterConsent { get; set; }

		public List<NewsletterSubscription> CurrentSubscriptions { get; set; } = new List<NewsletterSubscription>();

		public UserProfileIncompleteException()
			: this(string.Empty)
		{
		}

		public UserProfileIncompleteException(string razerId)
			: base("The user profile is not complete")
		{
			RazerId = razerId;
		}

		public UserProfileIncompleteException(XDocument doc)
			: this(doc.Element("UserProfileIncompleteException"))
		{
		}

		public UserProfileIncompleteException(XElement element)
		{
			RazerId = (string)element.Element("RazerId");
			RazerIdAutoGenerated = (bool)element.Element("RazerIdAutoGenerated");
			NeedsNewsLetterConsent = (bool)element.Element("NeedsNewsLetterConsent");
			foreach (XElement item in element.Element("Subscriptions").Elements())
			{
				CurrentSubscriptions.Add(new NewsletterSubscription(item));
			}
		}

		public XElement Serialize()
		{
			return new XElement("UserProfileIncompleteException", new XElement("RazerId", RazerId), new XElement("RazerIdAutoGenerated", RazerIdAutoGenerated), new XElement("NeedsNewsLetterConsent", NeedsNewsLetterConsent), new XElement("Subscriptions", CurrentSubscriptions.Select((NewsletterSubscription x) => x.Serialize())));
		}
	}
}
