namespace CustomerFWU2Point5
{
	public enum eState
	{
		STATE_NULL = 0,
		STATE_WAITING_DEVICE = 1,
		STATE_WAITING_BOOTLOADER = 2,
		STATE_PROCESSING_DATA = 3,
		STATE_PROCESSING_DATA_PASS = 4,
		STATE_PROCESSINGDATA_FAIL = 5,
		STATE_ERASING_FLASH = 6,
		STATE_ERASING_FLASH_PASS = 7,
		STATE_ERASING_FLASH_FAIL = 8,
		STATE_DOWNLOADING_DATA = 9,
		STATE_DOWNLOADING_DATA_PASS = 10,
		STATE_DOWNLOADING_DATA_FAIL = 11,
		STATE_VERIFYING_FIRMWARE = 12,
		STATE_VERIFYING_FIRMWARE_PASS = 13,
		STATE_VERIFYING_FIRMWARE_FAIL = 14,
		STATE_ENTER_BL = 15,
		STATE_EXIT_BL = 16,
		STATE_EXIT_NordicBL = 17,
		STATE_FLASHFW_BEFORE = 18,
		STATE_FLASHFW_AFTER = 19,
		STATE_SUCCESS = 20,
		STATE_FAILED = 21,
		STATE_LAST = 21,
		NUM_STATES = 22
	}
}
